### ISSUE TITLE
Long startup delay on some newer laptops with bluetooth

### ISSUE THREAD

**Issue by ottre** [eudev-project/eudev#132]
antiX is reporting a bluetooth issue [here](http://forum.mepiscommunity.org/viewtopic.php?t=39914).

I don't know the details, but I can say that antiX is the only Debian-based distribution using eudev. Devuan has made it clear they will not be using eudev.

Since Debian is enormously popular (ranked #2 on distrowatch), I think it's worth contacting them to reproduce and fix the issue.

**Comment by BitJam** [comment]
I had the problem on a Dell XPS-13 with Intel skylake.   I know others had the problem on other systems.  It was the standard  annoying 1-minute delay that used to occur with udev a few years back.  In addition, I couldn't figure out how to enable logging so I couldn't track down the problem further.  For me the only fix that worked was to go back to udev.  IIRC, removing bluetooth software did not help even though it helped others.

Without the delay I can get to Bash in 8 seconds.  With the delay it takes close to a minute and 8 seconds.

I use uedev on Gentoo (but not on the XPS-13).     When I looked into the problem I think we only had an older version of eudev available via Debian which was released before the skylake hardware was released.   

I've attached a zip file with the hardware aliases and the output of lspci -nn.  Some of my hardware was not in our pci.ids file so some names are missing from the lspci output.
[xps-13.zip](https://github.com/gentoo/eudev/files/254371/xps-13.zip)

Another frustration (although this may be standard now) is that blacklisting was ignored, at least for KMS video drivers.  ISTM that if eudev/udev ignores blacklisting then blacklisting is pretty pointless.

**Comment by ottre** [comment]
antiX uses a custom kernel with CONFIG_FW_LOADER_USER_HELPER=y.

I wonder if [adding a stub to always fail firmware loading](http://article.gmane.org/gmane.linux.embedded.yocto.meta-ti/7775/) would fix it.

If so, maybe we just need to improve the documentation?

**Comment by ottre** [comment]
>Without the delay I can get to Bash in 8 seconds. With the delay it takes close to a minute and 8 seconds.

60 seconds is the default user-loading timeout, try running "cat /sys/class/firmware/timeout".

**Comment by blueness** [comment]
This is the first I'm seeing of this report.  It sounds like a newer device, that's responsible but the above report didn't really pin point it.  I'll update the hwdb and test a new release.  Can you guys test that?

**Comment by dolphinoracle** [comment]
also present with antiX on lenovo s21e laptop.

**Comment by blueness** [comment]
@dolphinoracle @ottre I've pushed some updates to the hwdb and rules, can you test them?

**Comment by blueness** [comment]
@dolphinoracle @ottre can you test eudev-3.2

**Comment by dolphinoracle** [comment]
@blueness - we are checking it out.  Will advise once I have it installed on the particular machine in question.

**Comment by weedy** [comment]
This just bit me in the ass over my iwlwifi card. Can you guys decide one way or the other?
For me I just nuked CONFIG_FW_LOADER_USER_HELPER

**Comment by blueness** [comment]
@weedy did nuking CONFIG_FW_LOADER_USER_HELPER work?

**Comment by weedy** [comment]
Yes it did.

```
# grep CONFIG_FW /usr/src/linux/.config
# CONFIG_FW_CFG_SYSFS is not set
CONFIG_FW_LOADER=y
CONFIG_FW_LOADER_USER_HELPER=y
# CONFIG_FW_LOADER_USER_HELPER_FALLBACK is not set
```
