### ISSUE TITLE
Use of asprintf() is not POSIX-compliant

### ISSUE THREAD

**Issue by ryao** [eudev-project/eudev#15]
Clang generates a few warnings about implicit declarations of asprintf():

```
libudev-enumerate.c:862:21: warning: implicit declaration of function 'asprintf' is invalid in C99 [-Wimplicit-function-declaration]
                if (asprintf(&child, "%s/%s", path, dent->d_name) < 0)
                    ^
libudev-device.c:1469:21: warning:   CC     libudev_la-libudev-monitor.lo
implicit declaration of function 'asprintf' is invalid in C99 [-Wimplicit-function-declaration]
                if (asprintf(&udev_device->devnode, "/dev/%s", devnode) < 0)
                    ^
```

```
libudev-enumerate.c:862:21: warning: implicit declaration of function 'asprintf' is invalid in C99 [-Wimplicit-function-declaration]
                if (asprintf(&child, "%s/%s", path, dent->d_name) < 0)
                    ^
libudev-device.c:1469:21: warning: implicit declaration of function 'asprintf' is invalid in C99 [-Wimplicit-function-declaration]
                if (asprintf(&udev_device->devnode, "/dev/%s", devnode) < 0)
                    ^
```

asprintf is a GNU extensions that is only declared when __GNU_SOURCE is set. That violates our goal of POSIX-compliance. I have elected to leave the warnings as-is in favor of removing them in a future patch.

**Comment by ericonr** [comment]
Is this still a concern? I don't see those warnings while compiling.

**Comment by blueness** [comment]
@ericonr Did you compile on musl?  Its not an issue on glibc, but I recall that it was an issue on musl.

**Comment by ericonr** [comment]
Yes, on musl.

That said, I can't find out where, if anywhere, `_GNU_SOURCE` is being passed to it... Or if we're just getting lucky with defaults. I will see if I can come up with a clean fix to be sure the issue never happens.

**Comment by ericonr** [comment]
The makefiles for files that use this function include this snippet, and `config.h` defines `_GNU_SOURCE`

```
	-include $(top_builddir)/config.h
```

So I think this can be closed.

**Comment by kaniini** [comment]
I think trying to be POSIX-compliant on something that is requiring `AF_NETLINK` is a little crazy.  If somebody wants to use this on non-Linux, they have to support `AF_NETLINK` anyway, so adding `asprintf` is not unreasonable to do at the same time.
