### ISSUE TITLE
Cross-compile udev

### ISSUE THREAD

**Issue by seymondy** [eudev-project/eudev#174]
I am trying to cross-compile udev for arm. From what I see there is no support for this inside configure. I imagine that the only solution is to generate the Makefile and modify the paths inside to point to my arm compiler. Any other idea?

**Comment by blueness** [comment]
I haven't tested cross compiling but 1) I know that eudev builds fine for arm and 2) I'm trying to stick to gnu autotool standards as closely as possible.  Can you post what you're doing and the errors you're encountering.

**Comment by seymondy** [comment]
Thank you for your quick response! I have managed to compile them, but my problem is that I need to obtain a shared object (or multiple ones, not quite sure). Currently I am obtaining a lot of library objects.

**Comment by orbea** [comment]
PR https://github.com/eudev-project/eudev/pull/261 should improve the situation here.

**Comment by bbonev** [comment]
PR #261 was closed. I suppose you found a way to x-compile. If not, please reopen and provide more info.
