### ISSUE TITLE
cross compile eudev

### ISSUE THREAD

**Issue by xfdzjz** [eudev-project/eudev#179]
When I was trying to cross compile the terminal show me this
checking for m4... /usr/bin/m4
checking arpa/inet.h usability... no
checking arpa/inet.h presence... no
checking for arpa/inet.h... no
configure: error: *** POSIX header not found

my configure command is ./configure  --host=x86_64-w64-mingw32  --prefix=/home/jiazhi/evan/eudev-3.2.9

what should I do, do I need to install any lib?

**Comment by xfdzjz** [comment]
And I have find the inet.h uder /usr/include/arpa/inet.h

**Comment by bbonev** [comment]
I see no point in cross compiling `eudev` for mingw(32|64) - there is no way the result to be useful because `eudev` depends on linux kernel functionality.
