### ISSUE TITLE
Crypto partitions missing from /dev/disk/by-label/

### ISSUE THREAD

**Issue by lelgenio** [eudev-project/eudev#217]
```sh
$ lsblk /dev/sda2
/dev/sda2: UUID="xxxx" LABEL="CRYPTROOT" TYPE="crypto_LUKS" PARTUUID="xxxx"
$ ls /dev/disk/by-label/
ROOT  BOOT
```

Is `rules/60-persistent-storage.rules` missing `crypto` on `ENV{ID_FS_USAGE}`?:
```udev
ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{ID_FS_LABEL_ENC}=="?*", SYMLINK+="disk/by-label/$env{ID_FS_LABEL_ENC}"
```

**Comment by bbonev** [comment]
Thanks for reporting this.

The issue will be addressed by the next merge of the rules.d; it is strange how the previous merge missed that, the original change dates back to 2018:

https://github.com/systemd/systemd/commit/f2bd752215cba2f90697edd7e3ff5e859a6b9a4c
