### ISSUE TITLE
missing progs

### ISSUE THREAD

**Issue by yodayox** [eudev-project/eudev#234]
new rules from
https://github.com/eudev-project/eudev/commit/247724da450b3bb8ef8d1963288069941b5cd904
needs dmi_memory_id and fdio_id which, as i can see, are not available in udev-243 src 
extras from dmesg:
udevd[1567]: failed to execute '/lib/udev/dmi_memory_id' 'dmi_memory_id': No such file or directory
udevd[1613]: failed to execute '/lib/udev/fido_id' 'fido_id': No such file or directory

**Comment by bbonev** [comment]
Thanks for the report. We will include the missing programs and that will most probably justify another pre-release.

**Comment by yodayox** [comment]
not sure that (fido_id & memory_id) will ever work on eudev - requires a tons of systemd craps :-(

**Comment by ArsenArsen** [comment]
> not sure that (fido_id & memory_id) will ever work on eudev - requires a tons of systemd craps :-(

It doesn't. It requires libsystemd, which is just common code for all systemd executables. We have related code here: https://github.com/eudev-project/eudev/tree/master/src/shared. Upstream dmi_memory_id.c doesn't look too bad to copy into our tree.
