### ISSUE TITLE
undefined reference to `epoll_create1'

### ISSUE THREAD

**Issue by navinagaraj** [eudev-project/eudev#236]
Hi i tried to install latest version but i am facing this error any help. I attached the error log.
![eudev-3 2 11](https://user-images.githubusercontent.com/42691369/189829256-233716b1-2933-424d-81eb-d7f524f16261.png)

[eudev-3.2.11.log](https://github.com/eudev-project/eudev/files/9554197/eudev-3.2.11.log)

**Comment by bbonev** [comment]
What OS is that?

**Comment by navinagaraj** [comment]
Hi @bbonev I customization a os for PowerPC, the Kernel-2.6.26 , gcc-4.9.4 and uClibc-0.9.33.3-git,Debian distribution.

**Comment by ArsenArsen** [comment]
it'd appear uClibc doesn't provide these functions? and, according to linker output, doesn't implement a few others. maybe musl works for you?

**Comment by navinagaraj** [comment]
Thanks @ArsenArsen  for quick respons.
