### ISSUE TITLE
no db file to read /run/udev/data/c13:83: No such file or directory

### ISSUE THREAD

**Issue by dkwo** [eudev-project/eudev#244]
I have an issue where sometimes eudev does not bring up my laptop's trackpoint.
It'is on Void Linux, using runit and eudev, with musl libc.
I initially opened an issue with libinput, but now it looks more like it could be related to eudev (or runit race condition).
I have all the logs and details there, so I link to it: https://gitlab.freedesktop.org/libinput/libinput/-/issues/826

Any hints?
Thanks.

**Comment by dkwo** [comment]
A similar issue may be happening with the occasional `daemon.err: [   14.158240] udevd[290]: could not read from '/sys/module/pcc_cpufreq/initstate': No such device`.

**Comment by bbonev** [comment]
> `daemon.err: [   14.158240] udevd[290]: could not read from '/sys/module/pcc_cpufreq/initstate': No such device`

This is definitely not related to input.

Can you confirm the eudev version in your system?

**Comment by dkwo** [comment]
At the time of reporting, it was `eudev-3.2.11`.
In the meantime, it got updated to `eudev-3.2.12`, and I cannot reproduce neither of the errors presently.

**Comment by bbonev** [comment]
Thanks for the update! I am closing the issue
