### ISSUE TITLE
cd/dvd - lost 

### ISSUE THREAD

**Issue by yodayox** [eudev-project/eudev#245]
udevadm monitor is blind ( do not see any uevent ) when press the eject/load button 
so if i insert a disc in , i cannnot see the content of that disc UNLESS i manually do udevadm trigger
then, to eject the cd, need to do udevadm trigger again affter pressing the eject button .. lol
any ideea ?

**Comment by yodayox** [comment]
added on block-rules and that  fixed the problem(s)
ACTION=="add", ATTR{removable}=="1", ATTR{events_poll_msecs}=="-1", ATTR{events_poll_msecs}="2000"

**Comment by apteryks** [comment]
That fix used to live in Debian and Ubuntu: https://sources.debian.org/data/main/s/systemd/215-17%2Bdeb8u7/debian/patches/Set-default-polling-interval-on-removable-devices-as.patch, but was later dropped as systemd systems don't exhibit the problems, apparently.  I'll revive it and submit it upstream.
