### ISSUE TITLE
Any updates for libgudev/eudev?

### ISSUE THREAD

**Issue by masterovhell** [eudev-project/eudev#251]
After updating my Devuan system to Excalibur/Ceres, I subsequently got an update for libgudev which after rebooting makes it to where my keyboard and mouse no longer work. I posted about this initially and was told this package was having issues, at this point I'm holding off on updates in anticipation for a fix to this issue.

Just curious about any roadmaps or expectations.

Thanks.

**Comment by nekopsykose** [comment]
duplicate of #249

**Comment by masterovhell** [comment]
okay, i'll ask this in that issue.
