### ISSUE TITLE
CONTRIBUTING: update

### ISSUE THREAD

**Issue by spaette** [eudev-project/eudev#277]
It has vestiges from when it was a Gentoo project.

At some point it might be updated to be more consistent with the current development circumstance.

Notwithstanding the foregoing the below might be more understandable to the potential contributors.

CONTRIBUTING

```diff
	sure the correct authorship appears.  Reference any early commits
- 	by their full shaw:
+ 	by their 40-character SHA-1 hash:
```

**Comment by bbonev** [comment]
I'd rather use " by their commit hash", what do you think?

**Comment by spaette** [comment]
> "by their full commit hash"

Your suggestion is better.
