### ISSUE TITLE
build fails when gperf is not installed

### ISSUE THREAD

**Issue by rofl0r** [eudev-project/eudev#75]
experienced with the latest release tarball

```
checking for gperf... no
configure: error: *** gperf not found
```

is gperf even used somewhere ? if not the dependency should be removed

if yes, the generated C files should be distributed as part of the "make dist" process, so that the user does not need having gperf installed just to generate a single file

**Comment by fjaell** [comment]
in eudev 3.0 the configure option --disable-keymap has been removed, so it's no longer possible to bypass the gperf issue.
That means eudev depends on gperf now! Not very nice, would be really helpful if we could find a way to avoid this.

**Comment by blueness** [comment]
Good point.  Right now I have to follow upstream more closely for the kdbus cuttover, so I'm been dropping some of the legacy stuff.  I wasn't thinking of gperf dependency.

Any suggestions?

**Comment by bbonev** [comment]
`gperf` is a hard dependency since quite a long time. No suggestion came for changing that during the last 6+ years, so closing.
